spring.application.name=civicpulse-backend
server.port=8080

# H2 File-based Persistent Database
spring.datasource.url=jdbc:h2:file:./data/civicpulse;AUTO_RECONNECT=TRUE;AUTO_SERVER=TRUE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=civicpulse2026

# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=false

# Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
app.security.jwt.secret=94a08da1fecbb6e8b46990538c7b50b2a8d3876bcb2eefba85d18d41fe0b66bd
app.security.jwt.expiration=86400000

# CORS Configuration
app.cors.allowed-origins=http://localhost:5173,http://localhost:3000

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Add external Gemini api key here for AI features
gemini.api.key=AIzaSyBpe2F9wNzW2qnULp1Bf_9DnKwwlYZ5FOI

# Increase request size for Base64 images
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB
server.tomcat.max-http-post-size=20MB
spring.codec.max-in-memory-size=20MB
